// <auto-generated />
using CPRG214.MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CPRG214.MVC.Data.Migrations
{
    [DbContext(typeof(AssetContext))]
    [Migration("20210212231005_CreateAssetsDB")]
    partial class CreateAssetsDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CPRG214.MVC.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("RentalProperty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetTypeId = 1,
                            Description = "Dell Inspirion Desktop, 10th Gen.",
                            Manufacturer = "Dell, Inc.",
                            Model = "3000 Series",
                            SerialNumber = "DDCWRP208S",
                            TagNumber = "AST100001"
                        },
                        new
                        {
                            Id = 2,
                            AssetTypeId = 1,
                            Description = "HP Pavilion All-in-One PC (Non-touch)",
                            Manufacturer = "Hewlett-Packard",
                            Model = "Pavilion",
                            SerialNumber = "9EE87AAABL",
                            TagNumber = "AST100002"
                        },
                        new
                        {
                            Id = 3,
                            AssetTypeId = 2,
                            Description = "Acer AOPEN CH1 19.5\"Monitor",
                            Manufacturer = "Acer",
                            Model = "AOPEN",
                            SerialNumber = "UMIC1AA002",
                            TagNumber = "AST200001"
                        },
                        new
                        {
                            Id = 4,
                            AssetTypeId = 2,
                            Description = "LG UltraGear FHD HDR 24\" Monitor",
                            Manufacturer = "LG",
                            Model = "UltraGear",
                            SerialNumber = "24GN600-B",
                            TagNumber = "AST200002"
                        },
                        new
                        {
                            Id = 5,
                            AssetTypeId = 3,
                            Description = "Cisco IP Phone 7821",
                            Manufacturer = "Cisco",
                            Model = "IP Phone",
                            SerialNumber = "CIS-7821-2",
                            TagNumber = "AST300001"
                        },
                        new
                        {
                            Id = 6,
                            AssetTypeId = 3,
                            Description = "Polycom SoundStation2 - Non-Expandable",
                            Manufacturer = "Polycom",
                            Model = "SoundStation2",
                            SerialNumber = "2200-16000-001",
                            TagNumber = "AST300002"
                        });
                });

            modelBuilder.Entity("CPRG214.MVC.Domain.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssetType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Desktop Computer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Computer Monitor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phone"
                        });
                });

            modelBuilder.Entity("CPRG214.MVC.Domain.Asset", b =>
                {
                    b.HasOne("CPRG214.MVC.Domain.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("CPRG214.MVC.Domain.AssetType", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
